// src/App.svelte
<script lang="ts">
	import hljs from 'highlight.js/lib/core';
	import gqlLanguage from 'highlight.js/lib/languages/graphql.js';
	import jsonLanguage from 'highlight.js/lib/languages/json';
	import xmlLanguage from 'highlight.js/lib/languages/xml';
	import 'highlight.js/styles/atom-one-dark.css';

	import * as prettier from 'prettier';
	import parserGraphql from 'prettier/plugins/graphql';
	import {
		append,
		responsePayloadHighlighted,
		responsePayloadJSONPathFilter,
		setResponsePayloadJSONPathFilter,
		settings,
		endpointUrlFilter,
		setEndpointUrlFilter,
	} from './store';
	import { fixtures } from './store/fixtures';
	import { entries, setCurrentRequestItem, currentRequestItem } from './store';
	import type { Entry, GQLEntry, HAREntry, HTTPEntry, RequestItem } from './types';
	import { isGQLEntry, isGraphQL, parseGQLEntry, parseHTTPEntry } from './utils';

	import RequestDetails from './EntryDetails.svelte';
	import RequestItemList from './RequestItemList.svelte';
	import type { FormEventHandler } from 'svelte/elements';
	import Settings from './Settings.svelte';

	hljs.registerLanguage('graphql', gqlLanguage);
	hljs.registerLanguage('json', jsonLanguage);
	hljs.registerLanguage('xml', xmlLanguage);

	const responsePayloadJSONChangeHandler: FormEventHandler<HTMLInputElement> = function (event) {
		console.log('responsePayloadJSONChangeHandler');
		if (!event.target) {
			return;
		}
		setResponsePayloadJSONPathFilter(event.currentTarget.value);
		if ($currentRequestItem) {
			setCurrentRequestItem($currentRequestItem);
		}
	};

	function escapeRegExp(string: string) {
		return string.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
	}

	const acceptedMimeTypes = [/application\/json/, /text\/.*/, /image\/.*/];

	function isAcceptedEntry(entry: Entry) {
		return (
			entry.request.method !== 'OPTIONS' &&
			acceptedMimeTypes.findIndex((acceptedMimeTypeRegEx) => {
				return acceptedMimeTypeRegEx.test(entry.response.mimeType);
			}) >= 0
		);
	}

	async function normalizeEntry(entry: Entry): Promise<RequestItem> {
		let responsePayload: unknown = null;
		try {
			responsePayload = typeof entry.response.getResponse === 'function' ? await entry.response.getResponse() : null;
		} catch (error) {
			console.warn(`Unable to get response body for entry: ${entry.id}`, error);
		}

		let requestType: RequestItem['type'] = 'Other';

		if (isGQLEntry(entry)) {
			requestType = 'GQL';
		} else if (/application\/json/.test(entry.response.mimeType)) {
			requestType = 'JSON';
		} else if (/text\/html/.test(entry.response.mimeType)) {
			requestType = 'XML';
		} else if (/text\/xml/.test(entry.response.mimeType)) {
			requestType = 'XML';
		} else if (/image\/svg\+xml.*/.test(entry.response.mimeType)) {
			requestType = 'SVG';
		} else if (/image\/.*/.test(entry.response.mimeType)) {
			requestType = 'IMG';
		}

		let requestItem: RequestItem;
		if (requestType === 'GQL') {
			const e = entry as GQLEntry;
			requestItem = {
				id: e.id,
				timestamp: e.timestamp,
				name: `${e.request.operationType} ${e.request.name}`,
				type: 'GQL',
				method: e.request.method,
				headers: e.request.headers,
				time: e.time,
				requestDomain: e.request.url,
				requestQueryString: null,
				requestQueryStringCode: null,
				requestGQLQuery: await prettier.format(e.request.query, {
					semi: false,
					parser: 'graphql',
					plugins: [parserGraphql],
				}),
				requestGQLQueryCode: hljs.highlight(
					await prettier.format(e.request.query, {
						semi: false,
						parser: 'graphql',
						plugins: [parserGraphql],
					}),
					{ language: 'graphql' },
				).value,
				requestGQLVariables: JSON.stringify(e.request.variables, null, 3),
				requestGQLVariablesCode: hljs.highlight(JSON.stringify(e.request.variables, null, 3), { language: 'json' }).value,
				requestPostData: null,
				requestPostDataCode: null,
				responseStatusCode: e.response.status,
				responseStatusMessage: e.response.statusMessage,
				responsePayload: responsePayload ? responsePayload : 'No response',
				responseMimeType: e.response.mimeType,
			};
		} else {
			const e = entry as HTTPEntry;
			requestItem = {
				id: e.id,
				timestamp: e.timestamp,
				name: e.request.name,
				type: requestType,
				method: e.request.method,
				headers: e.request.headers,
				time: e.time,
				requestDomain: e.request.url.replace(new RegExp(`${escapeRegExp(e.request.pathname)}.*`), ''),
				requestQueryString: JSON.stringify(e.request.query, null, 3),
				requestQueryStringCode: hljs.highlight(JSON.stringify(e.request.query, null, 3), { language: 'json' }).value, // FIXME
				requestGQLQuery: null,
				requestGQLQueryCode: null,
				requestGQLVariables: null,
				requestGQLVariablesCode: null,
				requestPostData: e.request.body ? JSON.stringify(e.request.body, null, 3) : null,
				requestPostDataCode: e.request.body ? hljs.highlight(JSON.stringify(e.request.body, null, 3), { language: 'json' }).value : null,
				responseStatusCode: e.response.status,
				responseStatusMessage: e.response.statusMessage,
				responsePayload: responsePayload ? responsePayload : 'No response',
				responseMimeType: e.response.mimeType,
			};
		}
		return requestItem;
	}

	if (import.meta.env.DEV) {
		(async function () {
			for (const harEntry of fixtures) {
				// @ts-expect-error Incorrect types
				if (isGraphQL(harEntry)) {
					// @ts-expect-error Incorrect types
					const parsedEntries = await parseGQLEntry(harEntry);
					if (Array.isArray(parsedEntries)) {
						for (const parsedEntry of parsedEntries) {
							if (isAcceptedEntry(parsedEntry)) {
								append(await normalizeEntry(parsedEntry));
							}
						}
					} else {
						if (isAcceptedEntry(parsedEntries)) {
							append(await normalizeEntry(parsedEntries));
						}
					}
				} else {
					// @ts-expect-error Incorrect types
					const parsed = parseHTTPEntry(harEntry);
					if (isAcceptedEntry(parsed)) {
						append(await normalizeEntry(parsed));
					}
				}
			}
		})();
	} else {
		// @ts-expect-error Incorrect types
		browser.devtools.network.onRequestFinished.addListener(async (harEntry: HAREntry) => {
			if (isGraphQL(harEntry)) {
				const parsedEntries = await parseGQLEntry(harEntry);
				if (Array.isArray(parsedEntries)) {
					for (const parsedEntry of parsedEntries) {
						if (isAcceptedEntry(parsedEntry)) {
							append(await normalizeEntry(parsedEntry));
						}
					}
				} else {
					if (isAcceptedEntry(parsedEntries)) {
						append(await normalizeEntry(parsedEntries));
					}
				}
			} else {
				const parsed = parseHTTPEntry(harEntry);
				console.log('parsed: ', parsed, isAcceptedEntry(parsed));
				if (isAcceptedEntry(parsed)) {
					append(await normalizeEntry(parsed));
				}
			}
		});
	}
</script>

<div class="h-full text-xs">
	<div class="flex h-full flex-row items-stretch gap-x-2">
		<div class="flex w-[16rem] shrink-0 basis-[16rem] bg-primary-content flex-col border-r border-solid border-neutral justify-between">
			<div class="flex items-center border-b border-solid border-neutral">
				<input
					type="text"
					value={$endpointUrlFilter}
					placeholder="Filter by endpoint URL"
					class="w-full bg-transparent p-2 text-xs outline-none ring-0"
					oninput={(event) => setEndpointUrlFilter(event.currentTarget.value)}
				/>
				{#if $endpointUrlFilter}
					<button class="mr-2" onclick={() => setEndpointUrlFilter('')} aria-label="Clear endpoint URL filter">
						<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width={1.5} stroke="currentColor" class="h-4 w-4">
							<path stroke-linecap="round" stroke-linejoin="round" d="m9.75 9.75 4.5 4.5m0-4.5-4.5 4.5M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
						</svg>
					</button>
				{/if}
			</div>
			<RequestItemList requestItems={$entries.filter((entry) => {
					if (!$settings.filters.Img && !$settings.filters.GQL && !$settings.filters.JSON && !$settings.filters.XML && !$settings.filters.Other) {
						return true;
					}
					return (
						($settings.filters.Img && entry.type === 'IMG') ||
						($settings.filters.GQL && entry.type === 'GQL') ||
						($settings.filters.JSON && entry.type === 'JSON') ||
						($settings.filters.XML && entry.type === 'XML') ||
						($settings.filters.Other && entry.type === 'Other')
					);
				}).filter((entry) => {
					if (!$endpointUrlFilter) {
						return true;
					}
					const endpointUrl = `${entry.requestDomain}${entry.name}`.toLowerCase();
					return endpointUrl.includes($endpointUrlFilter.toLowerCase());
				})
				} {setCurrentRequestItem} currentRequestItem={$currentRequestItem} />

			<div class="flex items-center gap-2 mt-auto p-1 border-t border-solid border-neutral">
				<Settings />
			</div>
		</div>

		{#if $currentRequestItem}
			<RequestDetails
				requestItem={$currentRequestItem}
				responsePayloadHighlighted={$responsePayloadHighlighted}
				responsePayloadJSONPathFilter={$responsePayloadJSONPathFilter}
				{responsePayloadJSONChangeHandler}
			/>
		{/if}
	</div>
</div>

// src/app.tsx
import clsx from 'clsx';
import { formatRelative } from 'date-fns/formatRelative';
import { Header } from 'har-format';
import hljs from 'highlight.js/lib/core';
import gqlLanguage from 'highlight.js/lib/languages/graphql.js';
import jsonLanguage from 'highlight.js/lib/languages/json';
import 'highlight.js/styles/atom-one-dark.css';
import jp from 'jsonpath';
import * as prettier from 'prettier';
import parserGraphql from 'prettier/plugins/graphql';
import { Component, JSX, createEffect, createSignal } from 'solid-js';

import * as store from './store';
import { Entry, GQLEntry, HTTPEntry } from './types';
import { isGQLEntry } from './utils';

hljs.registerLanguage('graphql', gqlLanguage);
hljs.registerLanguage('json', jsonLanguage);

type RequestItem = {
	id: string;
	timestamp: number;
	name: string;
	type: string;
	method: string;
	headers: Array<Header>;
	requestQueryString: string;
	requestGQLQuery: string;
	requestGQLVariables: string;
	requestPostData: string;
	responsePayload: string;
};

function clearList() {
	store.setEntries([]);
}

async function normalizeEntry(entry: Entry): Promise<RequestItem> {
	let response = null;
	try {
		response = typeof entry.response.getResponse === 'function' ? await entry.response.getResponse() : null;
	} catch (error) {
		console.warn(`Unable to get response body for entry: ${entry.id}`, error);
	}

	let data: RequestItem;
	if (isGQLEntry(entry)) {
		const e = entry as GQLEntry;
		data = {
			id: e.id,
			timestamp: e.timestamp,
			name: `${e.request.operationType} ${e.request.name}`,
			type: 'GQL',
			method: e.request.method,
			headers: e.request.headers,
			requestQueryString: null,
			requestGQLQuery: await prettier.format(entry.request.query, {
				semi: false,
				parser: 'graphql',
				plugins: [parserGraphql],
			}),
			requestGQLVariables: JSON.stringify(e.request.variables, null, 3),
			requestPostData: null,
			responsePayload: response ? response : 'No response',
		};
	} else {
		const e = entry as HTTPEntry;
		data = {
			id: e.id,
			timestamp: e.timestamp,
			name: e.request.name,
			type: 'XHR',
			method: e.request.method,
			headers: e.request.headers,
			requestQueryString: JSON.stringify(e.request.query, null, 3),
			requestGQLQuery: null,
			requestGQLVariables: null,
			requestPostData: JSON.stringify(e.request.body, null, 3),
			responsePayload: response ? response : 'No response',
		};
	}
	return data;
}

const App: Component = () => {
	const [getEntries, setEntries] = createSignal([]);
	const [getSelectedEntry, setSelectedEntry] = createSignal(null);
	const [getResponsePayloadJSONPathFilter, setResponsePayloadJSONPathFilter] = createSignal(null);
	const [getResponsePayload, setResponsePayload] = createSignal(null);

	createEffect(async () => {
		const newEntries = [];
		for (const entry of store.entries) {
			newEntries.push(await normalizeEntry(entry));
		}
		setEntries(newEntries);
	});

	createEffect(function () {
		let payload = '';
		if (getSelectedEntry()?.responsePayload && getResponsePayloadJSONPathFilter()) {
			try {
				payload = jp.query(getSelectedEntry()?.responsePayload, getResponsePayloadJSONPathFilter());
			} catch (error) {
				console.log('jsonpath error', error);
			}
		} else if (getSelectedEntry()?.responsePayload) {
			payload = getSelectedEntry().responsePayload;
		}
		setResponsePayload(hljs.highlight(JSON.stringify(payload, null, 3), { language: 'json' }).value);
	});

	function responsePayloadJSONChangeHandler(event) {
		setResponsePayloadJSONPathFilter(event.target.value);
	}

	return (
		<div class="h-full text-xs">
			<div class="flex h-full flex-row items-stretch gap-x-2">
				<div class="flex w-[20rem] basis-[20rem] flex-col border-r border-solid border-accent">
					<div class="grow overflow-y-auto">
						{getEntries()
							.sort((a, b) => b.timestamp - a.timestamp)
							.map((entry) => {
								return (
									<button
										class={clsx('w-full p-2 text-left text-sm hover:bg-base-300/50', {
											'bg-base-300': entry.id === getSelectedEntry()?.id,
										})}
										onClick={() => setSelectedEntry(entry)}
										title={entry.name}
									>
										<div class="mb-2 overflow-hidden text-ellipsis whitespace-nowrap">{entry.name}</div>
										<div class="flex flex-row items-center gap-2">
											<div class="badge badge-primary badge-xs">{entry.type}</div>
											<div class="badge badge-secondary badge-xs">{entry.method}</div>
											<div class="text-xs text-base-content/50">{formatRelative(new Date(entry.timestamp), new Date())}</div>
										</div>
									</button>
								);
							})}
					</div>
					<div class="mt-auto border-t border-solid border-neutral bg-base-200 p-2">
						<button class="btn btn-neutral btn-xs" onClick={clearList}>
							Clear
						</button>
					</div>
				</div>

				{getSelectedEntry() ? (
					<>
						<div class="basis-3/6 overflow-y-auto border-r border-solid border-accent p-2">
							<div class="mb-2 italic text-gray-500">{getSelectedEntry().name}</div>
							<div class="mb-3">
								<h2 class="mb-2 text-sm">Headers</h2>
								<table>
									{getSelectedEntry().headers.map((header) => {
										return (
											<tr class="border-b border-solid border-gray-700">
												<td class="whitespace-nowrap py-1 pr-2 align-top">{header.name}</td>
												<td class="break-all">{header.value}</td>
											</tr>
										);
									})}
								</table>
							</div>
							{getSelectedEntry().requestQueryString && (
								<div class="mb-3">
									<h2 class="mb-2 text-sm">Query string</h2>
									<pre>
										<code class="hljs" innerHTML={hljs.highlight(getSelectedEntry().requestQueryString, { language: 'json' }).value}></code>
									</pre>
								</div>
							)}
							{getSelectedEntry().requestGQLQuery && (
								<div class="mb-3">
									<h2 class="mb-2 text-sm">GQL Query</h2>
									<pre>
										<code class="hljs" innerHTML={hljs.highlight(getSelectedEntry().requestGQLQuery, { language: 'graphql' }).value}></code>
									</pre>
								</div>
							)}
							{getSelectedEntry().requestGQLVariables && (
								<div class="mb-3">
									<h2 class="mb-2 text-sm">GQL Variables</h2>
									<pre>
										<code
											class="hljs"
											innerHTML={hljs.highlight(getSelectedEntry().requestGQLVariables, { language: 'json' }).value}
										></code>
									</pre>
								</div>
							)}
							{getSelectedEntry().requestPostData && (
								<div class="mb-3">
									<h2 class="mb-2 text-sm">POST data</h2>
									<pre>
										<code class="hljs" innerHTML={hljs.highlight(getSelectedEntry().requestPostData, { language: 'json' }).value}></code>
									</pre>
								</div>
							)}
						</div>

						<div class="flex basis-3/6 flex-col overflow-y-auto">
							<div class="grow overflow-y-auto p-2">
								{getSelectedEntry().responsePayload && (
									<pre>
										<code class="hljs" innerHTML={getResponsePayload()}></code>
									</pre>
								)}
							</div>
							<div class="mt-auto flex items-center justify-between border-t border-solid border-neutral bg-base-200">
								<input
									type="text"
									value={getResponsePayloadJSONPathFilter()}
									placeholder="Filter with JSONPath"
									class="bg-transparent p-2 outline-none ring-0"
									onChange={responsePayloadJSONChangeHandler}
								/>
								{getResponsePayloadJSONPathFilter() && (
									<button class="mr-2">
										<svg
											xmlns="http://www.w3.org/2000/svg"
											fill="none"
											viewBox="0 0 24 24"
											stroke-width={1.5}
											stroke="currentColor"
											class="h-6 w-6"
											onClick={() => setResponsePayloadJSONPathFilter('')}
										>
											<path
												stroke-linecap="round"
												stroke-linejoin="round"
												d="m9.75 9.75 4.5 4.5m0-4.5-4.5 4.5M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"
											/>
										</svg>
									</button>
								)}
							</div>
						</div>
					</>
				) : null}
			</div>
		</div>
	);
};

export default App;
